language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

before_install:

install:
  - pip install invoke
  - inv clean build package install
  -
script: inv unit && coveralls


deploy:
  - provider: script
    skip_cleanup: true
    skip_existing: true
    script: inv upload
    on:
        tags: true
        branch: master