language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install invoke
  - inv clean build install

script:
  - inv unit
  - coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: inv upload
    on:
        tags: true
        branch: master