language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

before_install:

install:
  - pip install invoke
  - inv clean build package install
script: inv unit && coveralls

stages:
  - test
  - deploy sandpit
  - deploy

jobs:
  include:
    - stage: deploy sandpit
      python: 3.6
      install: pip install invoke
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: inv upload-test
        on:
          tags: true
          branch: master
    - stage: deploy
      python: 3.6
      install: pip install invoke
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: inv upload
        on:
          tags: true
          branch: master

