language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

before_install:

install:
  - pip install invoke
  - inv clean build package install
  -
script: inv unit && coveralls


deploy:
  provider: pypi
  user: $TWINE_USERNAME
  password: $TWINE_PASSWORD
  distributions: "sdist bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
